// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package src

import (
	"jonathantyar/tokopedia-crawler/src/database"
	"jonathantyar/tokopedia-crawler/src/repository"
	"jonathantyar/tokopedia-crawler/src/service"
)

// Injectors from injector.go:

func InitializeTokopediaService() (service.ScrapperServiceInterface, error) {
	db, err := database.InitDB()
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductRepository(db)
	scrapperServiceInterface := service.NewScrapperServiceTokopedia(productRepository)
	return scrapperServiceInterface, nil
}
